version: '3.8'

services:
  mongodb:
    image: mongo:7.0-rc-jammy
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - database:/data/db
    networks:
      - backend
  
  api:
    build: ./api
    restart: unless-stopped
    ports:
      - 8080:8080
    networks:
      - backend
    depends_on:
      - mongodb

volumes: 
  database:

networks:
  backend:
