version: '3.8'

services:
  mongodb:
    image: mongo:7.0.2
    restart: unless-stopped
    ports:
      - 7017:27017
    volumes:
      - db:/data/db
    networks:
      - backend
  
  api:
    depends_on:
      - mongodb
    build: ./api
    restart: unless-stopped
    ports:
      - 6868:8080
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/node-boilerplate
    networks:
      - backend

volumes: 
  db:

networks:
  backend:
