version: '3.8'
services:
  node:
    restart: always
    build: ./api
    ports:
      - 8080:8080
    volumes:
      - ./:/code
  mongo:
    image: mongo:7.0.2
    ports:
      - 7017:27017
    volumes:
      - mongodb:/data/db
volumes:
 mongodb: