version: '3.8'

services:
  api:
    build: .
    image: api
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/database
    ports:
      - '8085:8085'
    depends_on:
      - mongodb
    volumes:
      - .:/src
    networks:
      - backend

  mongodb:
    image: mongo:7.0-rc-jammy
    ports:
      - '7017:27017'
    volumes:
      - mongodbdata:/data/db
    networks:
      - backend

volumes: 
  mongodbdata:

networks:
  backend:
    driver: bridge