version: '3.8'

services:
  mongodb:
    image: mongo:7.0-rc-jammy
    ports:
      - 27017:27017
    volumes:
      - database:/data/db
    networks:
      - backend
  
  api:
    depends_on:
      - mongodb
    build: ./api
    ports:
      - 8080:8080
    networks:
      - backend

volumes: 
  database:

networks:
  backend:
